
const PSReferenceList = [
    "AshPrime",
    "AtlasPrime",
    "BansheePrime",
    "BaruukPrime",
    "ChromaPrime",
    "EmberPrime",
    "EquinoxPrime",
    "FrostPrime",
    "GaraPrime",
    "GarudaPrime",
    "GaussPrime",
    "GrendelPrime",
    "HarrowPrime",
    "HildrynPrime",
    "HydroidPrime",
    "InarosPrime",
    "IvaraPrime",
    "KhoraPrime",
    "LavosPrime",
    "LimboPrime",
    "LokiPrime",
    "MagPrime",
    "MesaPrime",
    "MiragePrime",
    "NekrosPrime",
    "NezhaPrime",
    "NidusPrime",
    "NovaPrime",
    "NyxPrime",
    "OberonPrime",
    "OctaviaPrime",
    "ProteaPrime",
    "RevenantPrime",
    "RhinoPrime",
    "SarynPrime",
    "SevagothPrime",
    "TitaniaPrime",
    "TrinityPrime",
    "ValkyrPrime",
    "VaubanPrime",
    "VoltPrime",
    "WispPrime",
    "WukongPrime",
    "XakuPrime",
    "ZephyrPrime",
    


    "AcceltraPrime",
    "AstillaPrime",
    "BazaPrime",
    "BoarPrime",
    "BoltorPrime",
    "BratonPrime",
    "BurstonPrime",
    "CedoPrime",
    "CernosPrime",
    "CorinthPrime",
    "FulminPrime",
    "LatronPrime",
    "NagantakaPrime",
    "PantheraPrime",
    "ParisPrime",
    "PhantasmaPrime",
    "RubicoPrime",
    "ScourgePrime",
    "SomaPrime",
    "StradavarPrime",
    "StrunPrime",
    "SybarisPrime",
    "TenoraPrime",
    "TiberonPrime",
    "TigrisPrime",
    "TrumnaPrime",
    "VectisPrime",
    "ZhugePrime",



    "AfurisPrime",
    "AkariusPrime",
    "AkboltoPrime",
    "AkbroncoPrime",
    "AkjagaraPrime",
    "AklexPrime",
    "AkmagnusPrime",
    "AksomatiPrime",
    "AkstilettoPrime",
    "AkvastoPrime",
    "BallisticaPrime",
    "BroncoPrime",
    "EpitaphPrime",
    "EuphonaPrime",
    "HikouPrime",
    "HystrixPrime",
    "KnellPrime",
    "LexPrime",
    "MagnusPrime",
    "PanderoPrime",
    "PyranaPrime",
    "SicarusPrime",
    "SpiraPrime",
    "VastoPrime",
    "VeloxPrime",
    "ZaktiPrime",
    "ZylokPrime",

    "AnkyrosPrime",
    "BoPrime",
    "Cobra & CranePrime",
    "DakraPrime",
    "DestrezaPrime",
    "DualKamasPrime",
    "DualKeresPrime",
    "FangPrime",
    "FragorPrime",
    "GalatinePrime",
    "GlaivePrime",
    "GramPrime",
    "GuandaoPrime",
    "GunsenPrime",
    "KarystPrime",
    "KogakePrime",
    "KronenPrime",
    "MasseterPrime",
    "NamiSkylaPrime",
    "NikanaPrime",
    "NinkondiPrime",
    "OkinaPrime",
    "OrthosPrime",
    "PangolinPrime",
    "QuassusPrime",
    "ReaperPrime",
    "RedeemerPrime",
    "ScindoPrime",
    "Silva & AegisPrime",
    "TatsuPrime",
    "TekkoPrime",
    "TipedoPrime",
    "VenkaPrime",
    "VolnusPrime",

    "CorvasPrime",
    "LarkspurPrime",

    "CarrierPrime",
    "DethcubePrime",
    "HeliosPrime",
    "NautilusPrime",
    "ShadePrime",
    "WyrmPrime",

    "KavasaPrimeCollar",

    "OdonataPrime",
];

export default PSReferenceList;